### PR TITLE
Hector documentation website with `pkgdown`

### LINKED ISSUE #130: Wiki documentation versioning
how to link to releases?

### PR DESCRIPTION
**Pull request by ashiklom**
Closes #130 

This PR integrates the Hector documentation into the main Hector repo (rather than as a wiki submodule), and then renders it as a website with [`pkgdown`](https://pkgdown.r-lib.org/index.html). Here's the resulting [package website](https://ashiklom.github.io/hector/). The manual files from the wiki live in the [`vignettes/manual`](https://github.com/ashiklom/hector/tree/pkgdown/vignettes/manual) directory (as R markdown -- `.Rmd` -- files), and are rendered in the ["Manual" tab](https://ashiklom.github.io/hector/articles/manual/index.html). The `manual` name can be changed, but as far as I can tell, the files have to live in `vignettes` for `pkgdown` to automatically compile them. 

The files are rendered by GitHub pages, and updated automatically by Travis (see the `deploy` block in the R section). We could also explore the possibility of rendering the development and release code separately, which seems to be something that [`pkgdown` supports](https://pkgdown.r-lib.org/reference/build_site.html#development-mode).

Note that I had to adjust the links and some other markdown formatting in the documentation, but I haven't changed any of the content -- that will come in a later PR.

What do you all think?

Related to #280 and #130.

### CODE REVIEW

**Comment by bpbond** [comment]
I think that is _slick_. Wow. I have read a fair amount about `pkgdown` but not really seen it in action. Are there any disadvantages to this way versus the wiki? (I don't see any.)

**Comment by ashiklom** [comment]
> Are there any disadvantages to this way versus the wiki?

The key disadvantage is that this is harder to edit if you don't already know a little bit about Git/GitHub. The wiki can be edited directly from the browser, but editing these docs requires going through the full clone -> commit -> push -> PR process. That said, a _huge_ advantage (as pointed out in #130 and #294) is that documentation becomes inextricably tied to the current version of the code. In PEcAn, we've leveraged this idea to force (or at least strongly encourage) people submitting PRs with significant changes to also update the relevant documentation at the same time. I think there are also ways we configure the site to facilitate contributions through "Edit this page"-type links that point to GitHub's browser-based editing tools for that particular page.

On a more minor note, the `pkgdown` "Manual" page doesn't have a sidebar table of contents the way GitHub's wiki does, so we would have to maintain our own in the `index.Rmd` file. It's not hard to do, but we would have to actively maintain it.

**Comment by bpbond** [comment]
@rplzzz @cahartin @pralitp Any thoughts or comments on this?

**Comment by pralitp** [comment]
I have to admit I haven't been paying that much attention to the discussion.  I'll just defer to your judgment on this one.

**Comment by rplzzz** [comment]
Seems ok to me.  I've never been a big fan of the GitHub wiki anyhow.  It's always seemed more designed for sharing information among developers than for publishing documentation.

**Comment by bpbond** [comment]
OK, thanks all. Merging.

**Pull request merged**
