### PR TITLE
Remove trailing whitespace from source files

### PR DESCRIPTION
**Pull request by mnichol3**
Addresses #351 by stripping trailing whitespace from `.cpp`, `.hpp`, and `.R` files. This should put an end to PRs being bloated with whitespace changes when files are edited and saved in RStudio.

### CODE REVIEW

**Comment by ssmithClimate** [comment]
Should probably coordinate with others working on active PRs. Not sure if its easier on them to commit this now or after their PRs are in.

**Comment by bpbond** [comment]
@kdorheim OK to merge with #366 to follow up shortly?

**Comment by kdorheim** [comment]
👍👍 sounds good @bpbond

**Comment by bpbond** [comment]
Thanks @mnichol3

**Pull request merged**
