### PR TITLE
Backport halocarbon fix

### PR DESCRIPTION
**Pull request by rgieseke**
This pull request adds the fix from #201 to the rc1.2 branch as well. (That would it make it easier to update this in pyhector as well.)

### CODE REVIEW

**Comment by cahartin** [comment]
@rgieseke I have a meeting next week with the Hector team and I hope to address a a few issues/PR and make a new Hector release.  Thanks!

**Comment by rgieseke** [comment]
Many thanks, looking forward!

**Comment by cahartin** [comment]
@rgieseke We merged this into rc2.0.  Looking towards a rc2.0 release by the end of the month.  We are bypassing the rc1.2.

**Comment by rgieseke** [comment]
Great! Thanks, I'll close this then ...

**Pull request closed without merging**
