### PR TITLE
Fix ocean temp

### PR DESCRIPTION
**Pull request by cahartin**
this addresses issue #140

### CODE REVIEW

**Comment by rplzzz** [comment]
I have tested these changes on linux, and they seem to work.  Since this will change the model outputs, we will probably want to update the sample files in the output directory.

**Comment by rplzzz** [comment]
@cahartin I removed the commit that added the unwanted data file.  Could you double check to make sure that nothing we actually wanted was lost?  Also, you will need to resync the branch in your repository if you intend to do any additional development (such as updating the sample outputs).

**Comment by cahartin** [comment]
@rplzzz good point on the output files.

**Comment by cahartin** [comment]
closing this pull request since we have the addition of DOEClim

**Pull request closed without merging**
