### PR TITLE
OH Component Code Clarification

### PR DESCRIPTION
**Pull request by ssmithClimate**
Cosmetic change to code to clarify relationship between changes in CH4 concentrations and OH precursor emissions, parameter toh, and the OH lifetime. (Note, this corrects a sign error typo in Meinshausen etal 2011 Eq. A31). 

Output is identical to before.

### CODE REVIEW

**Comment by cahartin** [comment]
@ssmithClimate could you generate a quick plot to show that this didn't change results and post here?

**Comment by cahartin** [comment]
@ssmithClimate - can you post a few values showing that the output is indeed the same and that there aren't any changes downstream?

**Comment by ssmithClimate** [comment]
Graphs of CH4 concentrations and GMT. Both identical.
image

**Comment by cahartin** [comment]
thanks!! @ssmithClimate

**Pull request merged**
