### PR TITLE
Bring test_csv_file_reader.cpp up to date and re-enable it

### PR DESCRIPTION
**Pull request by bpbond**
See #450

### CODE REVIEW

**Comment by bpbond** [comment]
Huh!

Screen Shot 2022-11-03 at 7 55 46 AM

**Comment by bpbond** [comment]
Disabled one test:
```c++
TEST_F(TestCSVTableReader, WrongSeparatorInRow) {
    testFile << "Date," << testVarName << std::endl;
    testFile << "2;6" << std::endl;
    testFile.close();
    Core core(Logger::SEVERE, false, false);
    // TODO: the following line segfaults on GitHub Actions
    // ASSERT_THROW(reader.process(&core, testComponentName, testVarName), h_exception);
}
```

We can come back to this another day.

**Review by kdorheim — APPROVED** [review]
For the commented-out test should we open an issue as a reminder to address that is commented out, why it was commented out and the motivation for implementing it?

**Comment by bpbond** [comment]
@kdorheim Thanks. Re opening an issue, up to you. I was thinking that having that `TODO:` is enough for us to find it again.

**Pull request merged**
