### PR TITLE
Project lib target

### PR DESCRIPTION
**Pull request by pralitp**
Updates to Xcode and visual studio projects to include "lib" targets to hector.  This is necessary to be able to link to GCAM or otherwise.

### CODE REVIEW

**Comment by rplzzz** [comment]
Is it normal for these CI checks to be failing, or did these changes break them?

**Comment by bpbond** [comment]
Not normal. Where did these CI checks come from? I messed around with Travis for this repo ~1 month ago, but on a branch that was subsequently deleted. @pralitp did you add CI? Or maybe I pushed something to _master_ by mistake. (Currently ooo and can't easily check.)

**Comment by rplzzz** [comment]
I'll dig around and see what I can come up with.

**Comment by pralitp** [comment]
I don't know anything about it, it just showed up. This pull request is
just project files changes and no code changes.

**Comment by bpbond** [comment]
Ok I must screwed up. I'll go delete the Travis entry entirely.

**Comment by rplzzz** [comment]
Yeah, the deal is that once you enable the CI hook, github is going to try to run the service every time an event occurs.  Deleting the CI branch doesn't stop that from happening; it only ensures that the CI build can't possibly succeed because the CI configuration files (the travis.yml mentioned in the logs for the failed checks) have been removed.

I've deleted the Travis hook, so presumably we won't get any more of these messages.  I'm not sure what it takes to get the one here to go away.  The important thing is that it doesn't seem to be related to whether or not the code actually builds; it's being driven by whether or not the CI system is configured, which it isn't.

**Pull request merged**
