### PR TITLE
fix : convert trailing comments to single sline comments

### PR DESCRIPTION
**Pull request by gaelforget**
Seems safer since fewer parsers will support comments trailing section lines than single line comments.

With at least one parser,  [IniFile.jl](https://github.com/JuliaIO/IniFile.jl#readme), these comments lead to an incorrect read -- separating out the comments as single lines fixed it.

### CODE REVIEW

**Comment by bpbond** [comment]
Thanks @gaelforget . What's the use case for this? I.e., why would another parser be reading Hector's INI files?

**Comment by kdorheim** [comment]
@gaelforget, thanks for your interest in contributing to Hector! I guess I am curious as to why this change was only made for the `HFC4310_halocarbon`?

**Comment by gaelforget** [comment]
> 

Other comments were single line comments or after variable definitions & did not seem to cause any issue -- unlike these few comments placed after section definitions (`[HFC4310_halocarbon ]`).

**Comment by kdorheim** [comment]
This does not affect our miscellaneous scripts that are not tested as part of the CI (this is a todo #657) good to merge!

**Pull request merged**
