### PR TITLE
Ensure OUTPUT directory exists

### LINKED ISSUE #115: Output is silently discarded if `./output` does not exist
We dealt with a similar problem pertaining to the log files in #39.  This variant never surfaced before because when we ran from the hector install directory the output directory already existed and was populated with sample outputs.  Now that we can easily run from other locations, we see this unwanted behavior.

### PR DESCRIPTION
**Pull request by pralitp**
Refactor the logger util method `chk_logdir` into h_util instead and rename it to `ensure_dir_exists` so that we can use it to ensure the `OUTPUT_DIRECTORY` exists as well.  

Note, this really only pertains to command line hector, no from R.

This closes #115

### CODE REVIEW

**Comment by pralitp** [comment]
A demonstration that this works as intended (I don't think this will be covered by tests, should it be?):

```
pralitp@WE42897 hector % rm -r output 
pralitp@WE42897 hector % ./src/hector inst/input/hector_ssp245.ini
ri Jan 14 10:11:21 2022:NOTICE:printLogHeader: hector version 3.0
Fri Jan 14 10:11:21 2022:NOTICE:main: hector wrapper start
Fri Jan 14 10:11:21 2022:NOTICE:main: Reading input file inst/input/hector_ssp245.ini
Fri Jan 14 10:11:21 2022:NOTICE:main: Creating and initializing the core.
Fri Jan 14 10:11:21 2022:WARNING:registerCapability: forcing is declaring capability FNH3 previously registered
Fri Jan 14 10:11:21 2022:NOTICE:main: Setting data in the core.
Fri Jan 14 10:11:21 2022:NOTICE:main: Adding visitors to the core.
Fri Jan 14 10:11:21 2022:NOTICE:main: Calling prepareToRun()
Fri Jan 14 10:11:21 2022:NOTICE:prepareToRun: Computing dependencies and re-ordering components...
Fri Jan 14 10:11:21 2022:NOTICE:prepareToRun: Preparing to run...
Fri Jan 14 10:11:21 2022:NOTICE:prepareToRun: Spinning up model...
Fri Jan 14 10:11:21 2022:NOTICE:run_spinup: Carbon model is spun up after 352 steps
Fri Jan 14 10:11:21 2022:NOTICE:run_spinup: Model spun up after 352 steps
Fri Jan 14 10:11:21 2022:NOTICE:main: Running the core.
Fri Jan 14 10:11:21 2022:NOTICE:run: Running...
Fri Jan 14 10:11:22 2022:NOTICE:main: Hector wrapper end
pralitp@WE42897 hector % ls output 
outputstream_ssp245.csv	tracking_ssp245.csv
pralitp@WE42897 hector % rm -r output 
pralitp@WE42897 hector % touch output
pralitp@WE42897 hector % ./src/hector inst/input/hector_ssp245.ini
ri Jan 14 10:11:39 2022:NOTICE:printLogHeader: hector version 3.0
Fri Jan 14 10:11:39 2022:NOTICE:main: hector wrapper start
Fri Jan 14 10:11:39 2022:NOTICE:main: Reading input file inst/input/hector_ssp245.ini
Fri Jan 14 10:11:39 2022:NOTICE:main: Creating and initializing the core.
Fri Jan 14 10:11:39 2022:WARNING:registerCapability: forcing is declaring capability FNH3 previously registered
Fri Jan 14 10:11:39 2022:NOTICE:main: Setting data in the core.
Fri Jan 14 10:11:39 2022:NOTICE:main: Adding visitors to the core.
* Program exception:
msg:  	Directory output/ does not exist and could not create it.
func: 	ensure_dir_exists
file: 	h_util.cpp
ffile:	h_util.cpp

line: 	79

```

**Comment by kdorheim** [comment]
wait sorry about all the confusion, did you branch off of land_tracking? if so then your PR should be merging into the branch.

**Comment by kdorheim** [comment]
@bpbond the github actions are getting suck on the same ubuntu issue 🙄 as #543. Okay to merge into land tracking?

**Comment by bpbond** [comment]
Yes please do, thanks.

**Pull request merged**
