### PR TITLE
Final v3 name changes

### PR DESCRIPTION
**Pull request by kdorheim**
Final output name changes & documeantion

### CODE REVIEW

**Comment by kdorheim** [comment]
@bpbond the one question I have is that for the output markdown I wrote a script that scrapes a cpp file to determine the R function names & the strings they return for the output article it does need some cleanup and documentation but do you think this is something that we would want to add to the package? Thoughts?

[R_outputs.txt](https://github.com/JGCRI/hector/files/8741192/R_outputs.txt)

**Comment by bpbond** [comment]
Sorry @kdorheim will look

**Comment by bpbond** [comment]
`output.Rmd` right?

**Comment by kdorheim** [comment]
yes please take a look at those rmd documents but should we keep the script I wrote to generate those? see [R_outputs.txt](https://github.com/JGCRI/hector/files/8741192/R_outputs.txt)

**Comment by bpbond** [comment]
That's slick @kdorheim - nice job. Yes, I would keep that script, if only as documentation for the future. Add a couple comments to it, and stick it into `misc/` or somewhere?

**Comment by kdorheim** [comment]
@bpbond okay to merge?

**Review by bpbond — APPROVED** [review]

**Pull request merged**
