### PR TITLE
BBL tweaks to outputstream page - minor

### PR DESCRIPTION
**Pull request by bpbond**

### CODE REVIEW

**Comment by bpbond** [comment]
@kdorheim Should we address/fix/close https://github.com/JGCRI/hector/issues/177 ?

**Comment by bpbond** [comment]
Is this page linked to from anywhere? 😕

**Comment by kdorheim** [comment]
> @kdorheim Should we address/fix/close #177 ?

Would fixing it be a big-time commitment? If not then I think we probably should

**Comment by kdorheim** [comment]
> Is this page linked to from anywhere? 😕

ohh hmm good point we could probably add a link to in in the build hector article where we discuss running command line, Xcode & VS hector. It is currently listed on the manual index and would be findable via the search bar once that is set up.

**Comment by bpbond** [comment]
How would I (or you) add that link?

**Review by leeyap — APPROVED** [review]
Nothing to add!

**Comment by bpbond** [comment]
OK I have assigned #177 to myself to take a hard look at.

**Comment by kdorheim** [comment]
> How would I (or you) add that link?

it is going to be something like [text related to article](ArticleName.html)

**Pull request merged**
