### PR TITLE
Carbon tracking vignette

### PR DESCRIPTION
**Pull request by leeyap**
Hi @bpbond,

Here is a draft of the carbon tracking vignette. Please let me know any edits/suggestions or if I missed anything. Thanks!

### CODE REVIEW

**Comment by bpbond** [comment]
@leeyap Can you change the base so that this PR is going to `tracking-vars`, not `master`? Thanks.

**Comment by bpbond** [comment]
Hi @leeyap -

Looks great! I have made some suggested edits for language and clarity and just pushed them (seemed easier); feel free to revert if something doesn't make sense to you.

There is one thing that will need to change — Kalyn and I are going to decide how we want to be able to set the tracking date programmatically from R (as opposed to editing the INI file; see #484 . Once that's done, we'll want to update the vignette to use that mechanism.

**Comment by leeyap** [comment]
@bpbond - the changes look good, thank you for that! 

Re: changing the date in R, that sounds good. Keep me posted on that and I'll update appropriately.

**Comment by bpbond** [comment]
Merging this so it's available over in #488

**Pull request merged**
