### PR TITLE
fix for double counting halocarbons

### PR DESCRIPTION
**Pull request by cahartin**
deleted the total forcing from halocarbons so it is not added to the 
total forcing.

### CODE REVIEW

**Comment by cahartin** [comment]
this addresses issue #200.

**Comment by cahartin** [comment]
I pulled out a random year of 2000 and plotted the difference between the old version of Hector and the new fixed Hector. We see a significant change in the total harlocarbon forcing, which has been deleted, resulting in a change in total radiative forcing, but we also see a small change in the forcing from CO2.  
rf_diff

**Comment by bpbond** [comment]
The CO2 change is presumably a feedback from previous years? Halocarbons changed, changing temperature, changing the terrestrial and ocean uptakes, changing CO2?

**Comment by rplzzz** [comment]
That sounds right to me.  The direction of the feedback change looks right, at least with respect to ocean uptake.  Higher temperatures should lead to less ocean absorption, which leaves more in the atmosphere.  Does terrestrial uptake go in the same direction?

**Comment by cahartin** [comment]
good idea @rplzzz, I added a comment in the code.  I don't see a problem with SO2.  We have 2 entries, one for indirect and one for direct with no total SO2.

**Comment by cahartin** [comment]
temp_diff


@rplzzz and @bpbond do you want to see some other variables, CO2, fluxes, etc?

**Comment by cahartin** [comment]
Just to be complete - atmospheric CO2.
co2_diff

**Pull request merged**
