### PR TITLE
Bring test_dependency_finder.cpp up to date and re-enable it

### PR DESCRIPTION
**Pull request by bpbond**
See #450 

@pralitp Re-enabling this Hector test file was triggering the following error from inside the googletest framework itself:

Screen Shot 2022-11-03 at 7 02 25 AM

...that stemmed from lines in `test_dependency_finder.cpp` like this:

Screen Shot 2022-11-03 at 7 07 53 AM

As you can see from the diff, I removed the ` << "Ordering: " << ordering << endl` end of the lines, after which things build and tests run fine. But I don't quite understand why.  Any insight? Are these lines now giving false positives, or was this something cosmetic that was fine to remove? Thanks.

### CODE REVIEW

**Comment by bpbond** [comment]
@kdorheim #450 can be closed after merging #652 #653 #654

**Comment by bpbond** [comment]
Thanks Pralit!

>Did we used to provide one somewhere and it got moved around in such a way that it is now out of scope

Not that I know of.

**Comment by bpbond** [comment]
P.S. I guess the only thing that's being lost is the custom failure message, so not urgent.

**Comment by pralitp** [comment]
I just reverted removing the custom messages and it built and ran the tests just fine.  However, I used the "HEAD" `googletest` as they recommended which might make a difference (or compiler: I used GCC 10.2)

@bpbond were you getting this locally or when enabled via GitHub Actions?  If the later I can try again in Docker to try to get closer to what GH actions is doing.

**Comment by bpbond** [comment]
It ran fine for me locally; only on GA was there a problem. 

Thanks!

**Review by kdorheim — COMMENTED** [review]
This is outside of my C++ knowledge, I think Pralit's feedback is more important here

**Review by kdorheim — APPROVED** [review]

**Comment by bpbond** [comment]
@pralitp OK, it runs fine on GA. I will revert those changes, update my local googletest, and push. OK to merge after that?

Thanks!

**Review by pralitp — APPROVED** [review]

**Comment by pralitp** [comment]
Great!  One minor fix I was going to suggest but can obviously go elsewhere is a doc fix:
```
diff --git a/vignettes/articles/BuildHector.Rmd b/vignettes/articles/BuildHector.Rmd
index 03c9690..69e7bea 100644
--- a/vignettes/articles/BuildHector.Rmd
+++ b/vignettes/articles/BuildHector.Rmd
@@ -164,7 +164,7 @@ To run build and run the Hector unit tests, type `make testing`
 and then

 ```
-./src/Testing/hector-unit-tests
+./src/unit-testing/hector-unit-tests
 ```

 ## Xcode (Mac OS X)
```

**Comment by bpbond** [comment]
Skipped tests since just a single doc file modified in c3f28fd3

**Pull request merged**
