### PR TITLE
Update copyright date per meeting with Sara Hunt

### LINKED ISSUE #663: From meeting with Sara Hunt
Update copyright notice in all source files to 2022.

### PR DESCRIPTION
**Pull request by bpbond**
Closes #663

### CODE REVIEW

**Comment by bpbond** [comment]
Hmm the unit testing target is erroring during compilation:
```
/usr/include/gtest/gtest-message.h:61:17: note:   no known conversion for argument 1 from ‘std::__cxx11::basic_stringstream<char>’ to ‘const testing::internal::Secret&’
[1138](https://github.com/JGCRI/hector/actions/runs/3596592417/jobs/6057663048#step:5:1139)
   61 | void operator<<(const testing::internal::Secret&, int);
[1139](https://github.com/JGCRI/hector/actions/runs/3596592417/jobs/6057663048#step:5:1140)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1140](https://github.com/JGCRI/hector/actions/runs/3596592417/jobs/6057663048#step:5:1141)
make[2]: *** [<builtin>: test_dependency_finder.o] Error 1
```
...which looks suspiciously like the gtest incompatibility issue I asked you about on Slack a couple months ago @pralitp . Looks like googletest 1.11.0-3 is being installed here 😦 

...and it's not working on my local machine either, which has 1.12.1_1.

**Comment by pralitp** [comment]
I suppose we did punt on it the first time.  Unfortunately It still works for me and using 1.12.1 and gcc 10.2.

I can't recall what changed which made it pass the last time.  I know I was speculating that it was stemming from our custom `operator<<`:
```
ostream& operator<<( ostream& out, const vector<string>& vec ) {
    if( vec.empty() ) {
        return out << "[]";
    }
    out << "[";
    vector<string>::const_iterator it = vec.begin();
    for( ; it != vec.end()-1; ++it ) {
        out << *it <<  ", ";
    }
    return out << *it << "]";
}
```

Was defined at the very end of `test_dependency_finder.cpp` and gtest need to instantiate it before it got there.  I was going to try to move it before we do any tests and see if it helped.  If it is failing to compile for you, do you mind trying it out?

**Comment by bpbond** [comment]
I tried moving the `operator<<` definition, didn't work, so punting on this for now — see #665 . Thanks!

**Comment by bpbond** [comment]
@kdorheim Should be ready for your review and merge.

**Comment by kdorheim** [comment]
Awesome I will take a look at it latter this afternoon!

**Review by kdorheim — APPROVED** [review]

**Pull request merged**
