### PR TITLE
Getting Hector set up for H2 emissions

### PR DESCRIPTION
**Pull request by kdorheim**
This PR is just to set Hector up for the H2 work, mainly to address [#748](https://github.com/JGCRI/hector/issues/748) and [#750](https://github.com/JGCRI/hector/issues/750), I am not sure if everything will make its way into the final release but 

* added tau oh as a variable that can be fetched from the R interface (should be pretty helpful during dev)
* registered H2 emissions as input to the OH component 
* H2 emissions set to 0 for all input csv tables as the moment 
* Added a H2 unit test (again this is useful during the dev phase and might be reorganized)

Things to confirm with others 
* H2 units - Tg?

### CODE REVIEW

**Comment by kdorheim** [comment]
Demonstrating OH lifetime is reported as output 

```
 ini <- system.file("input/hector_ssp245.ini", package = "hector")
dates <- 1750:2100

 hc <- newcore(ini)
 run(hc)
 out <- fetchvars(hc, dates = 1750:2100, vars = LIFETIME_OH())

head(out)
```

```
>     head(out)
             scenario year variable    value units
1 Unnamed Hector core 1750   TAU_OH 6.656159 Years
2 Unnamed Hector core 1751   TAU_OH 6.662276 Years
3 Unnamed Hector core 1752   TAU_OH 6.668394 Years
4 Unnamed Hector core 1753   TAU_OH 6.678406 Years
5 Unnamed Hector core 1754   TAU_OH 6.691402 Years
6 Unnamed Hector core 1755   TAU_OH 6.694948 Years
```

**Comment by kdorheim** [comment]
Demonstrating that OH lifetime can now be reported as output

```
ini <- system.file("input/hector_ssp245.ini", package = "hector")
dates <- 1750:2100

hc <- newcore(ini)
run(hc)
 out <- fetchvars(hc, dates = 1750:2100, vars = LIFETIME_OH())

 head(out)
```

```
>     head(out)
             scenario year variable    value units
1 Unnamed Hector core 1750   TAU_OH 6.656159 Years
2 Unnamed Hector core 1751   TAU_OH 6.662276 Years
3 Unnamed Hector core 1752   TAU_OH 6.668394 Years
4 Unnamed Hector core 1753   TAU_OH 6.678406 Years
5 Unnamed Hector core 1754   TAU_OH 6.691402 Years
6 Unnamed Hector core 1755   TAU_OH 6.694948 Years

```

**Comment by kdorheim** [comment]
H2 emissions can be changed but do not affect Hector's behavior yet... 

image

**Review by bpbond — APPROVED** [review]
Thanks for the good prep work!

**Pull request merged**
