### PR TITLE
Rtuneup

### PR DESCRIPTION
**Pull request by bpbond**
Nothing more humbling than reading your old code. Ugh.

A number of changes here: shifted to  `readr` (issue #84) and `dplyr` packages for reading and summarizing/combining data, respectively; checks for missing COMPARISON_DATA (issue #101); new `op_support.R` file. In summary, code is quite a bit faster, and somewhat more robust.

### CODE REVIEW

**Comment by bpbond** [comment]
@cahartin Let's try this on your system before merging.

**Comment by cahartin** [comment]
@bpbond when loading the comparison data, ocean ph has a unit of 1.  It looks like this is throwing an error:
 CMIP5/Hector_models_ph/hist/ensemble_mean_model.csv C:/Users/hart428/Documents/GitHub/hector/R/outputplotter/comparison_data/GMD_2015
Fri Aug 21 11:35:03 2015  -- 3246 observations
Fri Aug 21 11:35:03 2015  -- ctags: ocean
Fri Aug 21 11:35:03 2015  -- vtags: ph ph_hl ph_ll
 Show Traceback
 
 Rerun with Debug
 Error in eval(expr, envir, enclos) : 
  incompatible type (data index: 2, column: 'units', was collecting: integer (dplyr::Collecter_Impl<16>), incompatible with data of type: integer

**Comment by cahartin** [comment]
I can fix this on my end in the actual data, but it might be useful to set all units to a string or something like that?

**Comment by bpbond** [comment]
@cahartin - Slack: "Good morning. Can I come take a look at your script issue, maybe in an hour or so?"

**Pull request merged**
