### PR TITLE
Merge changes from gcam branch

### PR DESCRIPTION
**Pull request by rplzzz**
This branch contains all of the support for running Hector coupled to some other software.  The most noteworthy changes are: 
* support for running a specified number of years before returning control to the calling code
* support for passing emissions to components via the core sendMessage interface.
Once these changes have been merged, I would like to create another release that includes these capabilities, as anyone wanting to link Hector to another model will need them.

### CODE REVIEW

**Comment by rplzzz** [comment]
This merge also fixes #85 .

**Comment by rplzzz** [comment]
@bpbond, @cahartin, is there any objection to merging these changes into the hector master branch?  Also, once we do merge the changes, we should consider making another release, since the new functionality will be important for some intended uses.

**Comment by rplzzz** [comment]
Has anybody had a chance to look at this yet?

**Comment by cahartin** [comment]
not yet.  On it now to get Hector running again.

**Comment by cahartin** [comment]
@rplzzz and @bpbond, I ran the gcam branch under release and debug mode for 2 of the 4 rcps.  Everything works on the VS end with the changes. @bpbond do you think its safe to merge the branches?

**Comment by bpbond** [comment]
Sorry for the long delay. Yes, this seems fine--I'll merge it. Thanks @rplzzz !

**Pull request merged**
