### PR TITLE
Remove throw() specifications

### LINKED ISSUE #257: Remove 'throw' specs from Hector functions
Quoth @rplzzz in https://github.com/JGCRI/hector/pull/256#discussion_r219313212

>I can't remember if I brought this up before, but `throw` specifications were deprecated as of C++11, and will probably be removed from the language entirely in a few years. Sometime when we don't have a bunch of other changes going on (i.e., not now), we need to go through and remove all of these.

### PR DESCRIPTION
**Pull request by bpbond**
Remove all throw() specifications on functions. The only exceptions is `class h_exception : public std::exception` which apparently has to define `const char* what() const throw()`.

More information: https://stackoverflow.com/questions/13841559/deprecated-throw-list-in-c11

Closes #257

### CODE REVIEW

**Comment by bpbond** [comment]
@kdorheim I didn't touch any R code; it looks like for both the lint and test coverage tests,
>ERROR: configuration failed for package ‘textshaping’

🤷‍♂️

**Comment by bpbond** [comment]
Ah it looks like `textshaping` was [just updated](https://cran.r-project.org/web/packages/textshaping/index.html) and a Mac binary isn't yet available. People had this issue [back in October](https://github.com/r-lib/pkgdown/issues/1427#issuecomment-726755544) too, when it was lat updated.

**Comment by kdorheim** [comment]
> Ah it looks like `textshaping` was [just updated](https://cran.r-project.org/web/packages/textshaping/index.html) and a Mac binary isn't yet available. People had this issue [back in October](https://github.com/r-lib/pkgdown/issues/1427#issuecomment-726755544) too, when it was lat updated.

👎 on `textshaping` being out of date bleh, do you think we need to make sure that the version of `textshaping` being installed for the github actions is mac compatible? Or can we leave as is and it will be fixed whenever it becomes available?

**Review by kdorheim — APPROVED** [review]
Removing deprecated code, love to see it!

**Comment by bpbond** [comment]
@kdorheim I'd be inclined to merge this, given that non-R tests all pass and all R tests on my local machine...but fine too to wait until next week when hopefully the `textshaping` binary will be available. 

Up to you as PR reviewer and integrator  🙂

**Comment by kdorheim** [comment]
I am inclined to merge it as well `textshaping` wouldn't be catching anything related to the changes you've made and if is a persistent problem could be addressed by a separate PR, I'll merge now

**Pull request merged**
